create database DRCA;
use DRCA;



CREATE TABLE `DEPARTAMENTO` (
	`DEPARTAMENTO_ID` int(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`DEPARTAMENTO_ID`)
	);



CREATE TABLE `ALUNO` (
	`ALUNO_ID` int(11) NOT NULL AUTO_INCREMENT,
	`DEPARTAMENTO_ID` int(11) NOT NULL,
	PRIMARY KEY (`ALUNO_ID`),
	KEY `DEPARTAMENTO_FK` (`DEPARTAMENTO_ID`),
	FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `DEPARTAMENTO` (`DEPARTAMENTO_ID`)
	);