create database DRCA;
use DRCA;


DROP TABLE `DEPARTAMENTO`;

CREATE TABLE `DEPARTAMENTO` (
	`DEPARTAMENTO_ID` int(11) NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255),
	`SEC_GRADUACAO_ID` int(11),
	`SEC_POS_GRADUACAO_ID` int(11),	
	PRIMARY KEY (`DEPARTAMENTO_ID`),
	KEY `SEC_GRADUACAO_FK`  (`SEC_GRADUACAO_ID`),
	FOREIGN KEY (`SEC_GRADUACAO_ID`) REFERENCES `SEC_GRADUACAO` (`SEC_GRADUACAO_ID`),
	KEY `SEC_POS_GRADUACAO_FK`  (`SEC_POS_GRADUACAO_ID`),
	FOREIGN KEY (`SEC_POS_GRADUACAO_ID`) REFERENCES `SEC_POS_GRADUACAO` (`SEC_POS_GRADUACAO_ID`)
	);





DROP TABLE `ALUNO`;
CREATE TABLE `ALUNO` (
	`ALUNO_ID` int(11) NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255) NOT NULL,
	`DEPARTAMENTO_ID` int(11),
	`CREDS_CUMPRIDOS` int(11) NOT NULL,
	PRIMARY KEY (`ALUNO_ID`),
	KEY `DEPARTAMENTO_FK` (`DEPARTAMENTO_ID`),
	FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `DEPARTAMENTO` (`DEPARTAMENTO_ID`)
	);



CREATE TABLE `PROFESSOR` (
	`PROFESSOR_ID` int(11) NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255) NOT NULL,
	`DEPARTAMENTO_ID` int(11) NOT NULL,	
	PRIMARY KEY (`PROFESSOR_ID`),
	KEY `DEPARTAMENTO_FK` (`DEPARTAMENTO_ID`),
	FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `DEPARTAMENTO` (`DEPARTAMENTO_ID`)
	);


CREATE TABLE `ALUNO_DISCIPLINA`(
	`ALUNO_ID` int(11) NOT NULL,
	`DISCIPLINA_ID` int(11) NOT NULL,
	PRIMARY KEY (`ALUNO_ID`,`DISCIPLINA_ID`),
	KEY `FK_ALUNO_ID` (`ALUNO_ID`),
	KEY `FK_DISCIPLINA_ALUNO` (`DISCIPLINA_ID`),
	CONSTRAINT `FK_ALUNO_ID` FOREIGN KEY (`ALUNO_ID`) REFERENCES `ALUNO` (`ALUNO_ID`),
	CONSTRAINT `FK_DISCIPLINA_ALUNO` FOREIGN KEY (`DISCIPLINA_ID`) REFERENCES `DISCIPLINA` (`DISCIPLINA_ID`)
	
);


DROP TABLE `DISCIPLINA_ALUNO`;
CREATE TABLE `DISCIPLINA_ALUNO` (
	`DISCIPLINA_ID` int(11) NOT NULL,
	`ALUNO_ID` int(11) NOT NULL,
	PRIMARY KEY (`DISCIPLINA_ID`,`ALUNO_ID`),
	#UNIQUE KEY `ALUNO_ID_UNIQUE` (`ALUNO_ID`),
	KEY `FK_DA_DISCIPLINA` (`DISCIPLINA_ID`),
	KEY `FK_DA_ALUNO` (`ALUNO_ID`),
	CONSTRAINT `FK_DA_ALUNO` FOREIGN KEY (`ALUNO_ID`) REFERENCES `ALUNO` (`ALUNO_ID`),
	CONSTRAINT `FK_DA_DISCIPLINA` FOREIGN KEY (`DISCIPLINA_ID`) REFERENCES `DISCIPLINA` (`DISCIPLINA_ID`)
);



CREATE TABLE `SEC_GRADUACAO_DISCIPLINA` (
	`SEC_GRADUACAO_ID` int(11) NOT NULL,
	`DISCIPLINA_ID` int(11) NOT NULL,
	PRIMARY KEY (`SEC_GRADUACAO_ID`,`DISCIPLINA_ID`),
	UNIQUE KEY `DISCIPLINA_ID_UNIQUE` (`DISCIPLINA_ID`),
	KEY `FK_SECRETARIA` (`SEC_GRADUACAO_ID`),
	KEY `FK_DISCIPLINA` (`SEC_GRADUACAO_ID`),
	CONSTRAINT `FK_SEC_GRADUACAO` FOREIGN KEY (`SEC_GRADUACAO_ID`) REFERENCES `SEC_GRADUACAO` (`SEC_GRADUACAO_ID`),
	CONSTRAINT `FK_DISCIPLINA_GRADUACAO` FOREIGN KEY (`DISCIPLINA_ID`) REFERENCES `DISCIPLINA` (`DISCIPLINA_ID`)
);



DROP TABLE `SEC_GRADUACAO`;
CREATE TABLE `SEC_POS_GRADUACAO_DISCIPLINA` (
	`SEC_POS_GRADUACAO_ID` int(11) NOT NULL ,
	`DISCIPLINA_ID` int(11) NOT NULL ,
	PRIMARY KEY (`SEC_POS_GRADUACAO_ID`,`DISCIPLINA_ID`),
	UNIQUE KEY `DISCIPLINA_ID_UNIQUE` (`DISCIPLINA_ID`),
	KEY `FK_SECRETARIA` (`SEC_POS_GRADUACAO_ID`),
	KEY `FK_DISCIPLINA` (`SEC_POS_GRADUACAO_ID`),
	CONSTRAINT `FK_SEC_POS_GRADUACAO` FOREIGN KEY (`SEC_POS_GRADUACAO_ID`) REFERENCES `SEC_POS_GRADUACAO` (`SEC_POS_GRADUACAO_ID`),
	CONSTRAINT `FK_DISCIPLINA_POS_GRADUACAO` FOREIGN KEY (`DISCIPLINA_ID`) REFERENCES `DISCIPLINA` (`DISCIPLINA_ID`)
);








CREATE TABLE `SEC_GRADUACAO` (
	`SEC_GRADUACAO_ID` int(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`SEC_GRADUACAO_ID`)
	);



CREATE TABLE `SEC_POS_GRADUACAO` (
	`SEC_POS_GRADUACAO_ID` int(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`SEC_POS_GRADUACAO_ID`)
	);


CREATE TABLE `DISCIPLINA` (
	`DISCIPLINA_ID` int(11) NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255) NOT NULL,
	`MIN_CREDITOS` int(11) NOT NULL,
	`OBRIGATORIA` bool NOT NULL,
	`OFERECIDA` bool NOT NULL,	
	PRIMARY KEY (`DISCIPLINA_ID`)
);


















