create database DRCA;
use DRCA;



CREATE TABLE `DEPARTAMENTO` (
	`DEPARTAMENTO_ID` int(11) NOT NULL AUTO_INCREMENT,
	`SEC_GRADUACAO_ID` int(11),
	`SEC_POS_GRADUACAO_ID` int(11),
	PRIMARY KEY (`DEPARTAMENTO_ID`),
	KEY `SEC_GRADUACAO_FK`  (`SEC_GRADUACAO_ID`),
	FOREIGN KEY (`SEC_GRADUACAO_ID`) REFERENCES `SEC_GRADUACAO` (`SEC_GRADUACAO_ID`),
	KEY `SEC_POS_GRADUACAO_FK`  (`SEC_POS_GRADUACAO_ID`),
	FOREIGN KEY (`SEC_POS_GRADUACAO_ID`) REFERENCES `SEC_POS_GRADUACAO` (`SEC_POS_GRADUACAO_ID`)
	);



CREATE TABLE `ALUNO` (
	`ALUNO_ID` int(11) NOT NULL AUTO_INCREMENT,
	`DEPARTAMENTO_ID` int(11) NOT NULL,
	`CREDS_CUMPRIDOS` int(11) NOT NULL,
	PRIMARY KEY (`ALUNO_ID`),
	KEY `DEPARTAMENTO_FK` (`DEPARTAMENTO_ID`),
	FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `DEPARTAMENTO` (`DEPARTAMENTO_ID`)
	);





CREATE TABLE `SEC_GRADUACAO` (
	`SEC_GRADUACAO_ID` int(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`SEC_GRADUACAO_ID`)
	);



CREATE TABLE `SEC_POS_GRADUACAO` (
	`SEC_POS_GRADUACAO_ID` int(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`SEC_POS_GRADUACAO_ID`)
	);